name: 'SomeApp'
version: 0.0.2
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: '^0.1.0'
  rpc: '^0.5.0'
  mongo_dart: '^0.2.4'
  http: '>=0.11.1 <0.12.0'
  crypto: '>=0.9.0 <0.10.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  http_server: '^0.9.5+1'
dependency_overrides:
  uri: ^0.11.0
dev_dependencies:
  test: "^0.12.6+2"
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
